name: Continuous Integration with Maven on Linux

on:
   push:
   pull_request:

jobs:
   build:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            include:
             - java: 11
               additional-maven-args: > 
                 -Pjacoco,pit-mutation-testing
                 -DrepoToken=$COVERALLS_REPO_TOKEN
                 coveralls:report
             - java: 17
               additional-maven-args: >
                 -Pjacoco
                 sonar:sonar
                 -Dsonar.organization=giamberinigiulia
                 -Dsonar.projectKey=giamberinigiulia_AST
                 -Dsonar.host.url=https://sonarcloud.io
            
      name: Build with Java ${{matrix.java}}
      steps:
      -  uses: actions/checkout@v4
         with:
            fetch-depth: 0
      -  name: Set up JDK ${{matrix.java}}
         uses: actions/setup-java@v4
         with:
            java-version: ${{matrix.java}}
            distribution: temurin
      -  name: Cache Maven packages
         uses: actions/cache@v4
         with:
            path: |
               ~/.m2
               ~/.sonar/cache
            key: ${{runner.os}}-m2-${{hashFiles('**/pom.xml', '**/*.yml')}}
            restore-keys: ${{runner.os}}-m2-
      -  name: Build with Maven
         run: xvfb-run mvn verify ${{matrix.additional-maven-args}}
         env:
            COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
            SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
         working-directory: com.giulia.giamberini.tennis
      -  name: Archive PIT report
         uses: actions/upload-artifact@v4
         with: 
            name: PIT-report
            path: '**/target/pit-reports'